theme: jekyll-theme-cayman
github:
  is_project_page: false
  <a id="skip-to-content" href="#content">Skip to the content.</a>

    <header class="page-header" role="banner">
      <img src="https://github.com/hwsimpson33/pres2020/blob/gh-pages/flag-pic-1.jpg" alt="{{ page.title | default: site.title | default: site.github.repository_name }}" class="project-name" />
      <img src="{{ page.image | default: site.logo }}" alt="{{ page.title | default: site.title | default: site.github.repository_name }}" class="project-name" />
      <h2 class="project-tagline">{{ page.description | default: site.description | default: site.github.project_tagline }}</h2>
      {% if site.github.is_project_page %}
        <a href="{{ site.github.repository_url }}" class="btn">View on GitHub</a>
