theme: jekyll-theme-cayman
title: Soumil Hooda
github:
  is_project_page: false
footer_content: "Copyright &copy; Soumil Hooda. Distributed by an <a href=\"https://https://github.com/soumilhooda/SoumilH/blob/main/LICENSE">GNU License.</a>"
  


